const rawUseCases = [
  {
    code: "UC01",
    slug: "01-xem-noi-dung-cong-khai",
    name: "Xem nội dung công khai",
    actors: ["Người dùng"],
    details: ["Mở trang công khai", "Xem danh mục khóa học", "Xem khóa học", "Xem giảng viên", "Xem bài viết", "Xem học viên vinh danh"],
    classes: ["Product", "Category", "Teacher", "Blog", "BlogCategory", "StudentStudy"],
    participants: ["Người dùng", "Frontend", "PublicController", "PublicService", "PublicRepository", "MongoDB"],
    description: "Người dùng truy cập các trang công khai để xem thông tin khóa học, giảng viên, bài viết và nội dung giới thiệu của hệ thống.",
    preconditions: ["Website hoặc ứng dụng đang hoạt động.", "Dữ liệu công khai đã được xuất bản.", "Người dùng có kết nối mạng ổn định."],
    mainFlow: [
      "Người dùng mở trang chủ hoặc chọn một mục nội dung công khai.",
      "Frontend hiển thị màn hình tương ứng và gửi yêu cầu lấy dữ liệu.",
      "PublicController nhận yêu cầu và kiểm tra tham số lọc hoặc phân trang.",
      "PublicService xác định loại nội dung cần hiển thị.",
      "PublicRepository truy vấn dữ liệu Product, Category, Teacher, Blog hoặc StudentStudy.",
      "Hệ thống chỉ lấy dữ liệu đang hoạt động, đã xuất bản và chưa bị xóa.",
      "Backend trả danh sách hoặc chi tiết nội dung công khai.",
      "Frontend hiển thị nội dung cho người dùng.",
    ],
    alternateFlows: [
      { code: "3a", title: "Bộ lọc không hợp lệ", steps: ["Hệ thống bỏ qua bộ lọc sai định dạng hoặc trả thông báo lỗi.", "Người dùng điều chỉnh điều kiện tìm kiếm."] },
      { code: "5a", title: "Không có dữ liệu phù hợp", steps: ["Hệ thống trả danh sách rỗng.", "Frontend hiển thị trạng thái không có nội dung."] },
      { code: "7a", title: "Không tải được nội dung", steps: ["Frontend thông báo lỗi tải dữ liệu.", "Người dùng có thể tải lại trang."] },
    ],
  },
  {
    code: "UC02",
    slug: "02-thanh-toan-khoa-hoc",
    name: "Thanh toán khóa học",
    actors: ["Người dùng"],
    details: ["Thực hiện thanh toán khóa học"],
    classes: ["PaymentOrder", "OrderItemSnapshot", "Cart", "CartItem", "Product", "User"],
    participants: ["Người dùng", "Frontend", "PaymentController", "PaymentService", "PaymentOrderRepo", "VNPay"],
    description: "Người dùng thanh toán khóa học đã chọn. Hệ thống tạo đơn, chuyển sang VNPay và cập nhật kết quả giao dịch sau khi nhận phản hồi.",
    preconditions: ["Người dùng đã đăng nhập.", "Khóa học cần mua còn khả dụng.", "Cổng thanh toán VNPay đã được cấu hình."],
    mainFlow: [
      "Người dùng mở danh sách hoặc trang chi tiết khóa học.",
      "Người dùng chọn khóa học cần thanh toán.",
      "Hệ thống kiểm tra trạng thái khóa học và quyền mua của người dùng.",
      "Người dùng nhấn thanh toán.",
      "Hệ thống kiểm tra khóa học, giá tiền và trạng thái người dùng.",
      "Hệ thống tạo đơn thanh toán ở trạng thái chờ thanh toán.",
      "Hệ thống chuyển người dùng sang phương thức hoặc cổng thanh toán.",
      "Hệ thống nhận kết quả thanh toán từ người dùng hoặc cổng thanh toán.",
      "Hệ thống xác minh giao dịch và cập nhật trạng thái đơn.",
      "Giao diện hiển thị kết quả thanh toán cho người dùng.",
    ],
    sequenceMessages: [
      ["Người dùng", "Frontend", "Chọn khóa học cần thanh toán"],
      ["Người dùng", "Frontend", "Nhấn thanh toán"],
      ["Frontend", "PaymentController", "POST tạo đơn thanh toán"],
      ["PaymentController", "PaymentService", "Kiểm tra phiên và dữ liệu đầu vào"],
      ["PaymentService", "PaymentOrderRepo", "Kiểm tra khóa học và quyền mua"],
      ["PaymentOrderRepo", "PaymentService", "Trả kết quả kiểm tra", true],
      ["PaymentService", "PaymentOrderRepo", "Tạo đơn chờ thanh toán"],
      ["PaymentOrderRepo", "PaymentService", "Trả mã đơn thanh toán", true],
      ["PaymentService", "VNPay", "Tạo URL thanh toán"],
      ["VNPay", "PaymentService", "Trả URL thanh toán", true],
      ["PaymentService", "PaymentController", "Trả URL và mã đơn", true],
      ["PaymentController", "Frontend", "Trả thông tin thanh toán", true],
      ["Frontend", "Người dùng", "Chuyển sang cổng thanh toán", true],
      ["VNPay", "PaymentController", "Callback kết quả giao dịch"],
      ["PaymentController", "PaymentService", "Xác minh chữ ký và mã đơn"],
      ["PaymentService", "PaymentOrderRepo", "Cập nhật trạng thái đơn"],
      ["PaymentOrderRepo", "PaymentService", "Trả đơn đã cập nhật", true],
      ["PaymentService", "PaymentController", "Trả kết quả giao dịch", true],
      ["PaymentController", "Frontend", "Trả trang kết quả", true],
      ["Frontend", "Người dùng", "Hiển thị kết quả thanh toán", true],
    ],
    alternateFlows: [
      { code: "1a", title: "Người dùng chưa đăng nhập", steps: ["Hệ thống chuyển người dùng về màn hình đăng nhập.", "Sau khi đăng nhập, người dùng thực hiện lại thanh toán."] },
      { code: "4a", title: "Khóa học không thể mua", steps: ["Hệ thống không tạo đơn thanh toán.", "Frontend hiển thị thông báo khóa học không khả dụng."] },
      { code: "8a", title: "Thanh toán thất bại hoặc bị hủy", steps: ["Hệ thống cập nhật đơn sang trạng thái thất bại hoặc hủy.", "Frontend hiển thị kết quả thanh toán không thành công."] },
    ],
  },
  {
    code: "UC03",
    slug: "03-cap-nhat-thong-tin-tai-khoan",
    name: "Cập nhật thông tin tài khoản",
    actors: ["Người dùng"],
    details: ["Xem hồ sơ", "Cập nhật họ tên", "Cập nhật số điện thoại", "Đổi mật khẩu", "Lưu thay đổi", "Đồng bộ giao diện"],
    classes: ["User", "SecurityAudit", "AdminPreference"],
    participants: ["Người dùng", "Frontend", "AccountController", "AccountService", "UserRepository", "MongoDB"],
    description: "Người dùng cập nhật thông tin cá nhân như họ tên, số điện thoại hoặc ảnh đại diện trong khu vực tài khoản.",
    preconditions: ["Người dùng đã đăng nhập.", "Tài khoản đang hoạt động.", "Dữ liệu cập nhật đáp ứng quy tắc nhập liệu của hệ thống."],
    mainFlow: [
      "Người dùng mở màn hình tài khoản cá nhân.",
      "Frontend tải thông tin hồ sơ hiện tại.",
      "Người dùng chỉnh sửa thông tin cần cập nhật.",
      "Frontend gửi dữ liệu đến AccountController.",
      "AccountController kiểm tra phiên và validate dữ liệu.",
      "AccountService cập nhật thông tin User tương ứng.",
      "Hệ thống lưu thay đổi và ghi nhận audit nếu cần.",
      "Frontend hiển thị thông tin tài khoản mới nhất.",
    ],
    alternateFlows: [
      { code: "5a", title: "Dữ liệu không hợp lệ", steps: ["Hệ thống trả lỗi validate.", "Người dùng chỉnh sửa lại thông tin."] },
      { code: "6a", title: "Không tìm thấy tài khoản", steps: ["Hệ thống từ chối cập nhật.", "Frontend yêu cầu người dùng đăng nhập lại."] },
      { code: "7a", title: "Lưu thay đổi thất bại", steps: ["Hệ thống giữ nguyên dữ liệu cũ.", "Frontend hiển thị thông báo thử lại sau."] },
    ],
  },
  {
    code: "UC04",
    slug: "04-xem-lich-su-thanh-toan",
    name: "Xem lịch sử thanh toán",
    actors: ["Người dùng"],
    details: ["Xem danh sách giao dịch", "Xem chi tiết đơn", "Đối chiếu khóa học đã mua"],
    classes: ["PaymentOrder", "OrderItemSnapshot", "Product", "User"],
    participants: ["Người dùng", "Frontend", "PaymentHistoryController", "PaymentHistoryService", "PaymentOrderRepo", "MongoDB"],
    description: "Người dùng xem các giao dịch thanh toán của chính mình và theo dõi trạng thái từng đơn thanh toán.",
    preconditions: ["Người dùng đã đăng nhập.", "Hệ thống có dữ liệu thanh toán của người dùng hoặc trả danh sách rỗng.", "Token truy cập còn hợp lệ."],
    mainFlow: [
      "Người dùng mở màn hình lịch sử thanh toán.",
      "Frontend gửi yêu cầu lấy danh sách giao dịch của tài khoản hiện tại.",
      "PaymentHistoryController xác thực phiên người dùng.",
      "PaymentHistoryService nhận bộ lọc trạng thái, từ khóa và phân trang.",
      "PaymentOrderRepo truy vấn các đơn thuộc về người dùng.",
      "Hệ thống tổng hợp thông tin đơn, khóa học và trạng thái thanh toán.",
      "Backend trả danh sách giao dịch hoặc chi tiết đơn.",
      "Frontend hiển thị lịch sử thanh toán cho người dùng.",
    ],
    alternateFlows: [
      { code: "4a", title: "Bộ lọc không hợp lệ", steps: ["Hệ thống trả lỗi tham số.", "Người dùng nhập lại điều kiện lọc."] },
      { code: "5a", title: "Không có giao dịch", steps: ["Hệ thống trả danh sách rỗng.", "Frontend hiển thị trạng thái chưa có thanh toán."] },
      { code: "7a", title: "Không được xem đơn của người khác", steps: ["Hệ thống từ chối truy cập.", "Frontend hiển thị thông báo không có quyền."] },
    ],
  },
  {
    code: "UC05",
    slug: "05-doi-mat-khau",
    name: "Đổi mật khẩu",
    actors: ["Người dùng"],
    details: ["Nhập mật khẩu hiện tại", "Nhập mật khẩu mới", "Xác nhận mật khẩu mới", "Kiểm tra chính sách mật khẩu", "Cập nhật mật khẩu", "Hủy phiên cũ nếu cần"],
    classes: ["User", "Session", "AccessToken", "SecurityAudit"],
    participants: ["Người dùng", "Frontend", "AccountController", "AccountService", "UserRepository", "SessionStore"],
    description: "Người dùng đổi mật khẩu tài khoản sau khi xác thực mật khẩu hiện tại và đáp ứng chính sách mật khẩu.",
    preconditions: ["Người dùng đã đăng nhập.", "Tài khoản đang hoạt động.", "Người dùng biết mật khẩu hiện tại."],
    mainFlow: [
      "Người dùng mở chức năng đổi mật khẩu.",
      "Người dùng nhập mật khẩu hiện tại, mật khẩu mới và xác nhận mật khẩu mới.",
      "Frontend gửi yêu cầu đổi mật khẩu đến AccountController.",
      "AccountController kiểm tra phiên và validate dữ liệu.",
      "AccountService xác minh mật khẩu hiện tại.",
      "Hệ thống kiểm tra chính sách độ mạnh của mật khẩu mới.",
      "UserRepository cập nhật mật khẩu đã băm.",
      "Hệ thống ghi audit và thông báo đổi mật khẩu thành công.",
    ],
    alternateFlows: [
      { code: "4a", title: "Thông tin nhập không hợp lệ", steps: ["Hệ thống hiển thị lỗi validate.", "Người dùng nhập lại mật khẩu."] },
      { code: "5a", title: "Mật khẩu hiện tại không đúng", steps: ["Hệ thống từ chối đổi mật khẩu.", "Hệ thống ghi audit đổi mật khẩu thất bại."] },
      { code: "6a", title: "Mật khẩu mới không đạt chính sách", steps: ["Hệ thống hiển thị quy tắc mật khẩu.", "Người dùng chọn mật khẩu mới khác."] },
    ],
  },
  {
    code: "UC06",
    slug: "06-xem-diem",
    name: "Xem điểm",
    actors: ["Học viên"],
    details: ["Xem bảng điểm", "Xem điểm kiểm tra", "Xem điểm trung bình", "Xem xếp hạng", "Xem trạng thái vinh danh", "Lọc theo lớp"],
    classes: ["StudentStudy", "StudySession", "ClassRoom", "Product", "User"],
    participants: ["Học viên", "Frontend", "StudyController", "StudyService", "StudentStudyRepo", "MongoDB"],
    description: "Học viên xem điểm học tập, điểm kiểm tra, điểm trung bình và xếp hạng của mình trong các lớp đã tham gia.",
    preconditions: ["Học viên đã đăng nhập.", "Học viên có hồ sơ học tập trong hệ thống.", "Dữ liệu điểm đã được giảng viên hoặc quản lý cập nhật."],
    mainFlow: [
      "Học viên mở màn hình điểm học tập.",
      "Frontend gửi yêu cầu lấy điểm của học viên hiện tại.",
      "StudyController xác thực phiên và phạm vi dữ liệu.",
      "StudyService xác định các lớp học viên đang theo học.",
      "StudentStudyRepo truy vấn điểm, buổi học và thông tin lớp.",
      "Hệ thống tính hoặc lấy điểm trung bình, xếp hạng và trạng thái vinh danh.",
      "Backend trả dữ liệu điểm cho frontend.",
      "Frontend hiển thị bảng điểm cho học viên.",
    ],
    alternateFlows: [
      { code: "4a", title: "Học viên chưa có lớp", steps: ["Hệ thống trả trạng thái chưa có hồ sơ học tập.", "Frontend hiển thị thông báo phù hợp."] },
      { code: "5a", title: "Chưa có điểm", steps: ["Hệ thống trả hồ sơ nhưng chưa có điểm.", "Frontend hiển thị trạng thái chờ cập nhật điểm."] },
      { code: "7a", title: "Truy cập sai phạm vi", steps: ["Hệ thống không trả dữ liệu của học viên khác.", "Frontend hiển thị thông báo không có quyền."] },
    ],
  },
  {
    code: "UC07",
    slug: "07-xem-lop-lich-hoc",
    name: "Xem lớp / lịch học",
    actors: ["Học viên"],
    details: ["Xem lịch học tuần", "Xem lớp đang học", "Xem phòng học", "Xem giảng viên phụ trách", "Xem trạng thái buổi học"],
    classes: ["ClassRoom", "StudentStudy", "StudySession", "Teacher", "Product"],
    participants: ["Học viên", "Frontend", "ScheduleController", "ScheduleService", "ClassRoomRepo", "MongoDB"],
    description: "Học viên xem danh sách lớp, lịch học, phòng học và thông tin giảng viên của các khóa học đã đăng ký.",
    preconditions: ["Học viên đã đăng nhập.", "Học viên có lớp học hoặc hồ sơ học tập liên quan.", "Dữ liệu lịch học đã được cập nhật."],
    mainFlow: [
      "Học viên mở màn hình lớp hoặc lịch học.",
      "Frontend gửi yêu cầu lấy lịch học theo tài khoản hiện tại.",
      "ScheduleController kiểm tra phiên học viên.",
      "ScheduleService truy vấn các lớp học viên tham gia.",
      "ClassRoomRepo lấy lịch, phòng học, giảng viên và khóa học liên quan.",
      "Hệ thống sắp xếp lịch học theo thời gian.",
      "Backend trả dữ liệu lớp và lịch học.",
      "Frontend hiển thị lịch học cho học viên.",
    ],
    alternateFlows: [
      { code: "4a", title: "Không có lớp học", steps: ["Hệ thống trả danh sách rỗng.", "Frontend hiển thị thông báo học viên chưa được xếp lớp."] },
      { code: "5a", title: "Lịch học chưa được cập nhật", steps: ["Hệ thống vẫn hiển thị thông tin lớp.", "Frontend thông báo lịch học đang chờ cập nhật."] },
      { code: "7a", title: "Phiên hết hạn", steps: ["Hệ thống yêu cầu đăng nhập lại.", "Học viên đăng nhập rồi thực hiện lại thao tác."] },
    ],
  },
  {
    code: "UC08",
    slug: "08-xem-thong-bao",
    name: "Xem thông báo",
    actors: ["Học viên", "Người dùng"],
    details: ["Xem danh sách thông báo", "Xem nội dung thông báo", "Đọc tất cả", "Lọc thông báo", "Cập nhật số chưa đọc"],
    classes: ["Notification", "User", "Role"],
    participants: ["Người dùng", "Frontend", "NotificationController", "NotificationService", "NotificationRepo", "MongoDB"],
    description: "Người dùng hoặc học viên xem các thông báo được gửi đến tài khoản của mình và cập nhật trạng thái đã đọc.",
    preconditions: ["Người dùng đã đăng nhập.", "Tài khoản có quyền truy cập khu vực thông báo.", "Dịch vụ thông báo đang hoạt động."],
    mainFlow: [
      "Người dùng mở danh sách thông báo.",
      "Frontend gửi yêu cầu lấy thông báo của tài khoản hiện tại.",
      "NotificationController xác thực phiên.",
      "NotificationService truy vấn thông báo theo người nhận.",
      "NotificationRepo lấy danh sách thông báo và số lượng chưa đọc.",
      "Backend trả danh sách thông báo cho frontend.",
      "Người dùng chọn đánh dấu đã đọc hoặc đọc tất cả nếu cần.",
      "Hệ thống cập nhật trạng thái thông báo và làm mới số chưa đọc.",
    ],
    alternateFlows: [
      { code: "4a", title: "Không có thông báo", steps: ["Hệ thống trả danh sách rỗng.", "Frontend hiển thị trạng thái chưa có thông báo."] },
      { code: "7a", title: "Thông báo không thuộc người dùng", steps: ["Hệ thống từ chối cập nhật trạng thái.", "Frontend tải lại danh sách thông báo."] },
      { code: "8a", title: "Cập nhật trạng thái thất bại", steps: ["Hệ thống giữ trạng thái cũ.", "Frontend thông báo người dùng thử lại."] },
    ],
  },
  {
    code: "UC09",
    slug: "09-quan-ly-lop-hoc",
    name: "Quản lý lớp học",
    actors: ["Giảng viên"],
    details: ["Thêm lớp học", "Sửa lớp học", "Khóa lớp học"],
    classes: ["ClassRoom", "StudentStudy", "StudySession", "Teacher", "User"],
    participants: ["Giảng viên", "Frontend", "ClassRoomController", "ClassRoomService", "ClassRoomRepo", "MongoDB"],
    description: "Giảng viên quản lý lớp học gồm thêm lớp, sửa thông tin lớp và khóa lớp khi cần.",
    preconditions: ["Giảng viên đã đăng nhập.", "Giảng viên có quyền quản lý lớp học.", "Dữ liệu khóa học, giảng viên, lịch học và phòng học cần thiết đã sẵn sàng."],
    mainFlow: [
      "Giảng viên mở màn hình quản lý lớp học.",
      "Frontend tải danh sách lớp học và dữ liệu hỗ trợ.",
      "ClassRoomController kiểm tra quyền quản lý lớp học.",
      "Giảng viên chọn thao tác thêm lớp, sửa lớp hoặc khóa lớp.",
      "Giảng viên nhập hoặc xác nhận thông tin cần xử lý.",
      "ClassRoomService kiểm tra dữ liệu lớp học, lịch học, phòng học và trạng thái.",
      "ClassRoomRepo lưu thay đổi vào dữ liệu ClassRoom.",
      "Frontend làm mới danh sách lớp học.",
    ],
    alternateFlows: [
      { code: "3a", title: "Không có quyền quản lý lớp", steps: ["Hệ thống từ chối thao tác.", "Frontend hiển thị thông báo không có quyền."] },
      { code: "6a", title: "Dữ liệu lớp học không hợp lệ", steps: ["Hệ thống không lưu thay đổi.", "Giảng viên chỉnh sửa lại thông tin lớp học."] },
      { code: "6b", title: "Lớp học đã bị khóa", steps: ["Hệ thống giữ nguyên trạng thái hiện tại.", "Frontend làm mới danh sách lớp học."] },
    ],
  },
  {
    code: "UC10",
    slug: "10-quan-ly-lich-hoc",
    name: "Quản lý lịch học",
    actors: ["Giảng viên"],
    details: ["Thêm lịch học", "Sửa lịch học", "Xóa lịch học"],
    classes: ["ClassRoom", "StudySession", "Teacher", "StudentStudy", "Notification"],
    participants: ["Giảng viên", "Frontend", "ScheduleController", "ScheduleService", "ScheduleRepo", "MongoDB"],
    description: "Giảng viên quản lý lịch học của lớp gồm thêm lịch, sửa lịch và xóa lịch khi không còn áp dụng.",
    preconditions: ["Giảng viên đã đăng nhập.", "Giảng viên có quyền quản lý lịch học.", "Lớp học cần thao tác đã tồn tại trong hệ thống."],
    mainFlow: [
      "Giảng viên mở màn hình quản lý lịch học.",
      "Frontend gửi yêu cầu lấy danh sách lớp và lịch học hiện có.",
      "ScheduleController kiểm tra quyền quản lý lịch học.",
      "Giảng viên chọn thao tác thêm lịch, sửa lịch hoặc xóa lịch.",
      "Frontend gửi thông tin lịch học hoặc yêu cầu xóa lịch đến backend.",
      "ScheduleService kiểm tra lớp học, lịch học, thời gian áp dụng và dữ liệu phòng học/link học.",
      "ScheduleRepo cập nhật dữ liệu lịch học của lớp.",
      "Frontend làm mới danh sách lịch học.",
    ],
    alternateFlows: [
      { code: "3a", title: "Không có quyền quản lý lịch", steps: ["Hệ thống từ chối thao tác.", "Frontend hiển thị thông báo không có quyền."] },
      { code: "6a", title: "Dữ liệu lịch học không hợp lệ", steps: ["Hệ thống không lưu thay đổi.", "Giảng viên chỉnh sửa lại lịch học."] },
      { code: "6b", title: "Lịch học không tồn tại hoặc đã bị xóa", steps: ["Hệ thống giữ nguyên dữ liệu hiện tại.", "Frontend làm mới danh sách lịch học."] },
    ],
  },
  {
    code: "UC11",
    slug: "11-quan-ly-hoc-vien",
    name: "Quản lý học viên",
    actors: ["Giảng viên", "Quản lý"],
    details: ["Thêm học viên", "Sửa học viên", "Khóa học viên"],
    classes: ["User", "StudentStudy", "ClassRoom", "Product", "Teacher"],
    participants: ["Giảng viên/Quản lý", "Frontend", "StudentController", "StudentService", "StudentRepo", "MongoDB"],
    description: "Giảng viên hoặc quản lý thêm học viên, sửa thông tin học viên và khóa học viên theo phạm vi quyền được cấp.",
    preconditions: ["Tác nhân đã đăng nhập.", "Tác nhân có quyền quản lý học viên.", "Dữ liệu học viên và lớp học có thể truy vấn."],
    mainFlow: [
      "Tác nhân mở màn hình quản lý học viên.",
      "Frontend gửi yêu cầu lấy danh sách học viên.",
      "StudentController kiểm tra quyền và phạm vi dữ liệu.",
      "StudentService truy vấn học viên theo bộ lọc.",
      "Tác nhân chọn thao tác thêm học viên, sửa học viên hoặc khóa học viên.",
      "Frontend gửi dữ liệu thao tác hoặc yêu cầu khóa học viên đến backend.",
      "StudentService validate dữ liệu và cập nhật User hoặc StudentStudy theo thao tác.",
      "Backend trả kết quả để frontend làm mới danh sách.",
    ],
    alternateFlows: [
      { code: "3a", title: "Không đủ quyền quản lý học viên", steps: ["Hệ thống từ chối thao tác.", "Frontend hiển thị thông báo không có quyền."] },
      { code: "7a", title: "Thông tin học viên không hợp lệ", steps: ["Hệ thống trả lỗi validate.", "Tác nhân chỉnh sửa lại dữ liệu."] },
      { code: "7b", title: "Học viên không tồn tại", steps: ["Hệ thống không thực hiện cập nhật.", "Frontend tải lại danh sách mới nhất."] },
    ],
  },
  {
    code: "UC12",
    slug: "12-quan-ly-thong-bao",
    name: "Quản lý thông báo",
    actors: ["Giảng viên", "Quản lý"],
    details: ["Xem danh sách thông báo", "Xem nội dung thông báo", "Lấy danh sách người nhận", "Tạo thông báo", "Gửi theo lớp hoặc vai trò", "Sửa trạng thái gửi", "Xóa thông báo", "Theo dõi trạng thái đọc"],
    classes: ["Notification", "User", "Role", "ClassRoom", "StudentStudy"],
    participants: ["Giảng viên/Quản lý", "Frontend", "NotificationController", "NotificationService", "UserRepository", "MongoDB"],
    description: "Giảng viên hoặc quản lý tạo, gửi và theo dõi thông báo đến người nhận trong phạm vi được phép.",
    preconditions: ["Tác nhân đã đăng nhập.", "Tác nhân có quyền gửi hoặc quản lý thông báo.", "Danh sách người nhận có thể truy vấn."],
    mainFlow: [
      "Tác nhân mở màn hình quản lý thông báo.",
      "Frontend tải danh sách người nhận phù hợp.",
      "Tác nhân nhập tiêu đề, nội dung và phạm vi gửi.",
      "Frontend gửi yêu cầu tạo thông báo.",
      "NotificationController kiểm tra quyền và validate dữ liệu.",
      "NotificationService xác định người nhận theo lớp, vai trò hoặc tài khoản.",
      "Hệ thống lưu Notification cho người nhận.",
      "Frontend hiển thị thông báo gửi thành công và cập nhật lịch sử gửi.",
    ],
    alternateFlows: [
      { code: "5a", title: "Nội dung thông báo không hợp lệ", steps: ["Hệ thống trả lỗi validate.", "Tác nhân chỉnh sửa tiêu đề hoặc nội dung."] },
      { code: "6a", title: "Không có người nhận phù hợp", steps: ["Hệ thống không tạo thông báo.", "Frontend hiển thị thông báo không tìm thấy người nhận."] },
      { code: "7a", title: "Lưu thông báo thất bại", steps: ["Hệ thống không ghi dữ liệu gửi.", "Tác nhân thực hiện lại thao tác sau."] },
    ],
  },
  {
    code: "UC13",
    slug: "13-dang-ky-dang-nhap",
    name: "Đăng ký, đăng nhập",
    actors: ["Người dùng", "Học viên", "Giảng viên", "Quản lý", "Admin"],
    details: ["Đăng ký tài khoản", "Đăng nhập", "Kiểm tra email và mật khẩu", "Tạo token", "Lấy vai trò và quyền", "Ghi audit đăng nhập"],
    classes: ["User", "Session", "AccessToken", "Role", "UserRole", "SecurityAudit"],
    participants: ["Người dùng", "Frontend", "AuthController", "AuthService", "UserRepository", "SessionStore"],
    description: "Tác nhân đăng ký hoặc đăng nhập để sử dụng các chức năng cần xác thực trong hệ thống.",
    preconditions: ["Hệ thống xác thực đang hoạt động.", "Với đăng nhập, tài khoản đã tồn tại và đang hoạt động.", "Với đăng ký, email chưa được sử dụng."],
    mainFlow: [
      "Tác nhân mở màn hình đăng ký hoặc đăng nhập.",
      "Tác nhân nhập thông tin theo yêu cầu.",
      "Frontend gửi thông tin đến AuthController.",
      "AuthController validate email, mật khẩu và dữ liệu liên quan.",
      "AuthService kiểm tra tài khoản hoặc tạo tài khoản mới.",
      "Hệ thống lấy vai trò, quyền và tạo phiên truy cập.",
      "Backend trả access token, refresh token và thông tin người dùng.",
      "Frontend lưu phiên đăng nhập và điều hướng vào khu vực phù hợp.",
    ],
    alternateFlows: [
      { code: "4a", title: "Thông tin đăng nhập không hợp lệ", steps: ["Hệ thống hiển thị lỗi nhập liệu.", "Tác nhân nhập lại thông tin."] },
      { code: "5a", title: "Email hoặc mật khẩu không đúng", steps: ["Hệ thống từ chối đăng nhập.", "Hệ thống ghi audit đăng nhập thất bại."] },
      { code: "5b", title: "Email đăng ký đã tồn tại", steps: ["Hệ thống không tạo tài khoản mới.", "Frontend yêu cầu dùng email khác hoặc đăng nhập."] },
    ],
  },
  {
    code: "UC14",
    slug: "14-dashboard-thong-ke",
    name: "Dashboard thống kê",
    actors: ["Quản lý", "Admin"],
    details: ["Xem tổng quan doanh thu", "Thống kê học viên", "Thống kê lớp học", "Biểu đồ xu hướng", "Quick rows"],
    classes: ["DashboardResponse", "PaymentOrder", "StudentStudy", "User", "ClassRoom", "Product"],
    participants: ["Manager", "Frontend", "DashboardController", "DashboardService", "DashboardRepo", "MongoDB"],
    description: "Quản lý hoặc Admin xem các chỉ số tổng quan về doanh thu, học viên, lớp học và hoạt động của hệ thống.",
    preconditions: ["Tác nhân đã đăng nhập.", "Tác nhân có quyền xem dashboard.", "Dữ liệu thống kê có thể truy vấn từ hệ thống."],
    mainFlow: [
      "Tác nhân mở màn hình dashboard.",
      "Frontend gửi yêu cầu lấy dữ liệu thống kê.",
      "DashboardController kiểm tra quyền truy cập.",
      "DashboardService xác định các chỉ số cần thống kê.",
      "DashboardRepo tổng hợp dữ liệu thanh toán, học viên, lớp học và khóa học.",
      "Hệ thống tính các chỉ số và biểu đồ cần hiển thị.",
      "Backend trả DashboardResponse cho frontend.",
      "Frontend hiển thị số liệu, biểu đồ và quick rows.",
    ],
    alternateFlows: [
      { code: "3a", title: "Không có quyền xem dashboard", steps: ["Hệ thống từ chối truy cập.", "Frontend hiển thị thông báo không có quyền."] },
      { code: "5a", title: "Không có dữ liệu thống kê", steps: ["Hệ thống trả chỉ số bằng 0 hoặc danh sách rỗng.", "Frontend vẫn hiển thị dashboard ở trạng thái trống."] },
    ],
  },
  {
    code: "UC15",
    slug: "15-quan-ly-bai-viet",
    name: "Quản lý bài viết",
    actors: ["Quản lý", "Admin"],
    details: ["Xem danh sách bài viết", "Xem bài đã xóa", "Tạo bài viết", "Cập nhật bài viết", "Upload ảnh", "Xóa mềm hoặc khôi phục"],
    classes: ["Blog", "BlogCategory", "User", "Permission"],
    participants: ["Manager", "Frontend", "BlogController", "BlogService", "BlogRepo", "MongoDB"],
    description: "Quản lý hoặc Admin tạo, cập nhật, xuất bản, xóa và khôi phục bài viết trong hệ thống.",
    preconditions: ["Tác nhân đã đăng nhập.", "Tác nhân có quyền quản lý bài viết.", "Danh mục bài viết cần dùng đã tồn tại nếu tạo hoặc sửa bài."],
    mainFlow: [
      "Tác nhân mở màn hình quản lý bài viết.",
      "Frontend gửi yêu cầu lấy danh sách bài viết.",
      "BlogController kiểm tra quyền quản lý bài viết.",
      "Tác nhân chọn tạo, sửa, xóa, khôi phục hoặc xem chi tiết bài viết.",
      "Frontend gửi dữ liệu thao tác đến backend.",
      "BlogService validate tiêu đề, slug, danh mục và trạng thái xuất bản.",
      "BlogRepo lưu thay đổi vào cơ sở dữ liệu.",
      "Frontend cập nhật danh sách bài viết theo kết quả trả về.",
    ],
    alternateFlows: [
      { code: "3a", title: "Không có quyền quản lý bài viết", steps: ["Hệ thống từ chối thao tác.", "Frontend hiển thị thông báo không có quyền."] },
      { code: "6a", title: "Slug hoặc dữ liệu bài viết không hợp lệ", steps: ["Hệ thống trả lỗi validate.", "Tác nhân chỉnh sửa lại nội dung bài viết."] },
      { code: "7a", title: "Bài viết không tồn tại", steps: ["Hệ thống không thực hiện thao tác.", "Frontend tải lại danh sách bài viết."] },
    ],
  },
  {
    code: "UC16",
    slug: "16-quan-ly-danh-muc-bai-viet",
    name: "Quản lý danh mục bài viết",
    actors: ["Quản lý", "Admin"],
    details: ["Xem danh mục bài viết", "Tạo danh mục", "Sửa danh mục", "Đổi trạng thái", "Xóa mềm", "Khôi phục hoặc xóa cứng"],
    classes: ["BlogCategory", "Blog", "Permission", "SecurityAudit"],
    participants: ["Manager", "Frontend", "BlogCategoryController", "BlogCategoryService", "BlogCategoryRepo", "MongoDB"],
    description: "Quản lý hoặc Admin quản lý các danh mục dùng để phân loại bài viết trong hệ thống.",
    preconditions: ["Tác nhân đã đăng nhập.", "Tác nhân có quyền quản lý danh mục bài viết.", "Dữ liệu danh mục bài viết có thể truy cập."],
    mainFlow: [
      "Tác nhân mở màn hình danh mục bài viết.",
      "Frontend tải danh sách danh mục hiện có.",
      "Tác nhân chọn thêm, sửa, đổi trạng thái, xóa hoặc khôi phục danh mục.",
      "Frontend gửi yêu cầu đến BlogCategoryController.",
      "BlogCategoryController kiểm tra quyền và validate dữ liệu.",
      "BlogCategoryService kiểm tra trùng tên, slug và ràng buộc bài viết liên quan.",
      "BlogCategoryRepo lưu thay đổi.",
      "Frontend cập nhật danh sách danh mục bài viết.",
    ],
    alternateFlows: [
      { code: "5a", title: "Dữ liệu danh mục không hợp lệ", steps: ["Hệ thống trả lỗi validate.", "Tác nhân chỉnh sửa lại thông tin."] },
      { code: "6a", title: "Danh mục đang được sử dụng", steps: ["Hệ thống không cho xóa cứng nếu vi phạm ràng buộc.", "Tác nhân chọn xóa mềm hoặc xử lý bài viết liên quan."] },
      { code: "7a", title: "Danh mục không tồn tại", steps: ["Hệ thống không thực hiện thao tác.", "Frontend tải lại danh sách mới nhất."] },
    ],
  },
  {
    code: "UC17",
    slug: "17-xem-audit-bao-mat",
    name: "Xem audit bảo mật",
    actors: ["Quản lý", "Admin"],
    details: ["Xem audit đăng nhập", "Lọc theo hành động", "Lọc theo người dùng", "Lọc theo trạng thái", "Xem chi tiết request", "Phân trang"],
    classes: ["SecurityAudit", "User", "Role", "Permission"],
    participants: ["Manager", "Frontend", "SecurityAuditController", "SecurityAuditService", "SecurityAuditRepo", "MongoDB"],
    description: "Quản lý hoặc Admin xem nhật ký bảo mật để theo dõi đăng nhập, phân quyền và các thao tác nhạy cảm trong hệ thống.",
    preconditions: ["Tác nhân đã đăng nhập.", "Tác nhân có quyền xem audit bảo mật.", "Hệ thống đã ghi nhận SecurityAudit."],
    mainFlow: [
      "Tác nhân mở màn hình audit bảo mật.",
      "Frontend gửi yêu cầu lấy danh sách audit.",
      "SecurityAuditController kiểm tra quyền truy cập.",
      "Tác nhân nhập bộ lọc hành động, người dùng hoặc trạng thái nếu cần.",
      "SecurityAuditService chuẩn hóa bộ lọc và phân trang.",
      "SecurityAuditRepo truy vấn bản ghi audit phù hợp.",
      "Backend trả danh sách audit và thông tin phân trang.",
      "Frontend hiển thị nhật ký bảo mật cho tác nhân.",
    ],
    alternateFlows: [
      { code: "3a", title: "Không có quyền xem audit", steps: ["Hệ thống từ chối truy cập.", "Frontend hiển thị thông báo không có quyền."] },
      { code: "4a", title: "Bộ lọc không hợp lệ", steps: ["Hệ thống trả lỗi tham số.", "Tác nhân nhập lại điều kiện lọc."] },
      { code: "6a", title: "Không có bản ghi audit", steps: ["Hệ thống trả danh sách rỗng.", "Frontend hiển thị trạng thái chưa có dữ liệu."] },
    ],
  },
  {
    code: "UC18",
    slug: "18-xem-audit-thanh-toan",
    name: "Xem audit thanh toán",
    actors: ["Quản lý", "Admin"],
    details: ["Xem toàn bộ thanh toán", "Lọc theo provider", "Lọc theo trạng thái", "Tìm theo mã thanh toán", "Xem chi tiết giao dịch", "Phân trang"],
    classes: ["PaymentOrder", "OrderItemSnapshot", "User", "Product"],
    participants: ["Manager", "Frontend", "PaymentAuditController", "PaymentAuditService", "PaymentOrderRepo", "MongoDB"],
    description: "Quản lý hoặc Admin xem và đối chiếu toàn bộ lịch sử thanh toán của hệ thống.",
    preconditions: ["Tác nhân đã đăng nhập.", "Tác nhân có quyền xem audit thanh toán.", "Dữ liệu thanh toán đã được ghi nhận trong hệ thống."],
    mainFlow: [
      "Tác nhân mở màn hình audit thanh toán.",
      "Frontend gửi yêu cầu lấy danh sách giao dịch.",
      "PaymentAuditController kiểm tra quyền truy cập.",
      "Tác nhân nhập bộ lọc provider, trạng thái hoặc mã thanh toán nếu cần.",
      "PaymentAuditService chuẩn hóa bộ lọc và phân trang.",
      "PaymentOrderRepo truy vấn các giao dịch phù hợp.",
      "Backend trả danh sách giao dịch và chi tiết liên quan.",
      "Frontend hiển thị audit thanh toán cho tác nhân.",
    ],
    alternateFlows: [
      { code: "3a", title: "Không có quyền xem audit thanh toán", steps: ["Hệ thống từ chối truy cập.", "Frontend hiển thị thông báo không có quyền."] },
      { code: "4a", title: "Tham số lọc không hợp lệ", steps: ["Hệ thống trả lỗi tham số.", "Tác nhân nhập lại bộ lọc."] },
      { code: "6a", title: "Không có giao dịch phù hợp", steps: ["Hệ thống trả danh sách rỗng.", "Frontend hiển thị trạng thái không có dữ liệu."] },
    ],
  },
  {
    code: "UC19",
    slug: "19-quan-ly-danh-muc-khoa-hoc",
    name: "Quản lý danh mục khóa học",
    actors: ["Quản lý", "Admin"],
    details: ["Xem danh mục khóa học", "Xem danh mục đã xóa", "Thêm danh mục", "Sửa danh mục", "Xóa mềm", "Khôi phục hoặc xóa cứng"],
    classes: ["Category", "Product", "Permission", "SecurityAudit"],
    participants: ["Manager", "Frontend", "CategoryController", "CategoryService", "CategoryRepo", "MongoDB"],
    description: "Quản lý hoặc Admin tạo, cập nhật, xóa và khôi phục danh mục khóa học.",
    preconditions: ["Tác nhân đã đăng nhập.", "Tác nhân có quyền quản lý danh mục khóa học.", "Dữ liệu danh mục khóa học có thể truy vấn."],
    mainFlow: [
      "Tác nhân mở màn hình danh mục khóa học.",
      "Frontend tải danh sách danh mục.",
      "Tác nhân chọn thêm, sửa, xóa, khôi phục hoặc xóa cứng danh mục.",
      "Frontend gửi yêu cầu đến CategoryController.",
      "CategoryController kiểm tra quyền và validate dữ liệu.",
      "CategoryService kiểm tra trùng slug và ràng buộc khóa học liên quan.",
      "CategoryRepo lưu thay đổi vào cơ sở dữ liệu.",
      "Frontend cập nhật danh sách danh mục khóa học.",
    ],
    alternateFlows: [
      { code: "5a", title: "Dữ liệu danh mục không hợp lệ", steps: ["Hệ thống trả lỗi validate.", "Tác nhân chỉnh sửa lại thông tin danh mục."] },
      { code: "6a", title: "Danh mục đang có khóa học", steps: ["Hệ thống từ chối xóa cứng nếu còn ràng buộc.", "Tác nhân xử lý khóa học liên quan hoặc dùng xóa mềm."] },
      { code: "7a", title: "Danh mục không tồn tại", steps: ["Hệ thống không thực hiện thao tác.", "Frontend tải lại danh sách mới nhất."] },
    ],
  },
  {
    code: "UC20",
    slug: "20-quan-ly-khoa-hoc",
    name: "Quản lý khóa học",
    actors: ["Quản lý", "Admin"],
    details: ["Xem khóa học", "Xem khóa học đã xóa", "Thêm khóa học", "Sửa khóa học", "Upload ảnh", "Xóa mềm hoặc khôi phục"],
    classes: ["Product", "Category", "Teacher", "ClassRoom", "CartItem", "OrderItemSnapshot"],
    participants: ["Manager", "Frontend", "CourseController", "CourseService", "CourseRepo", "MongoDB"],
    description: "Quản lý hoặc Admin quản lý thông tin khóa học, danh mục, giảng viên phụ trách, giá và trạng thái xuất bản.",
    preconditions: ["Tác nhân đã đăng nhập.", "Tác nhân có quyền quản lý khóa học.", "Danh mục và giảng viên liên quan đã tồn tại nếu cần."],
    mainFlow: [
      "Tác nhân mở màn hình quản lý khóa học.",
      "Frontend tải danh sách khóa học.",
      "Tác nhân chọn thêm, sửa, xóa, khôi phục hoặc xem chi tiết khóa học.",
      "Frontend gửi dữ liệu thao tác đến CourseController.",
      "CourseController kiểm tra quyền và validate dữ liệu.",
      "CourseService kiểm tra danh mục, giảng viên, slug và dữ liệu ảnh.",
      "CourseRepo lưu thay đổi vào cơ sở dữ liệu.",
      "Frontend cập nhật danh sách khóa học theo kết quả trả về.",
    ],
    alternateFlows: [
      { code: "5a", title: "Dữ liệu khóa học không hợp lệ", steps: ["Hệ thống trả lỗi validate.", "Tác nhân chỉnh sửa lại thông tin khóa học."] },
      { code: "6a", title: "Danh mục hoặc giảng viên không tồn tại", steps: ["Hệ thống không lưu khóa học.", "Frontend hiển thị thông báo dữ liệu liên quan không hợp lệ."] },
      { code: "7a", title: "Khóa học đang có giao dịch hoặc lớp liên quan", steps: ["Hệ thống giới hạn thao tác xóa cứng.", "Tác nhân chọn xóa mềm hoặc xử lý ràng buộc trước."] },
    ],
  },
  {
    code: "UC21",
    slug: "21-quan-ly-giang-vien",
    name: "Quản lý giảng viên",
    actors: ["Quản lý", "Admin"],
    details: ["Xem giảng viên", "Xem chi tiết", "Thêm giảng viên", "Sửa thông tin", "Upload avatar", "Đổi trạng thái hoặc xóa"],
    classes: ["Teacher", "User", "Product", "ClassRoom", "StudentStudy"],
    participants: ["Manager", "Frontend", "TeacherController", "TeacherService", "TeacherRepo", "MongoDB"],
    description: "Quản lý hoặc Admin quản lý hồ sơ giảng viên, thông tin chuyên môn, trạng thái và các liên kết với khóa học hoặc lớp học.",
    preconditions: ["Tác nhân đã đăng nhập.", "Tác nhân có quyền quản lý giảng viên.", "Dữ liệu tài khoản hoặc hồ sơ giảng viên có thể truy vấn."],
    mainFlow: [
      "Tác nhân mở màn hình quản lý giảng viên.",
      "Frontend tải danh sách giảng viên.",
      "Tác nhân chọn thêm, sửa, đổi trạng thái, xóa hoặc xem chi tiết giảng viên.",
      "Frontend gửi dữ liệu thao tác đến TeacherController.",
      "TeacherController kiểm tra quyền và validate dữ liệu.",
      "TeacherService kiểm tra tài khoản liên quan và ràng buộc lớp/khóa học.",
      "TeacherRepo lưu thay đổi.",
      "Frontend cập nhật danh sách giảng viên.",
    ],
    alternateFlows: [
      { code: "5a", title: "Thông tin giảng viên không hợp lệ", steps: ["Hệ thống trả lỗi validate.", "Tác nhân chỉnh sửa lại dữ liệu."] },
      { code: "6a", title: "Giảng viên đang phụ trách lớp hoặc khóa học", steps: ["Hệ thống hạn chế xóa cứng.", "Tác nhân xử lý ràng buộc hoặc đổi trạng thái."] },
      { code: "7a", title: "Không tìm thấy giảng viên", steps: ["Hệ thống không thực hiện thao tác.", "Frontend tải lại danh sách mới nhất."] },
    ],
  },
  {
    code: "UC22",
    slug: "22-quan-ly-nguoi-dung",
    name: "Quản lý người dùng",
    actors: ["Admin"],
    details: ["Xem danh sách user", "Xem chi tiết user", "Tạo user", "Cập nhật user", "Đổi trạng thái", "Xóa hoặc khôi phục"],
    classes: ["User", "Role", "UserRole", "SecurityAudit"],
    participants: ["Admin", "Frontend", "UserController", "UserService", "UserRepository", "MongoDB"],
    description: "Admin quản lý tài khoản người dùng trong hệ thống, bao gồm tạo mới, cập nhật, khóa, xóa và khôi phục tài khoản.",
    preconditions: ["Admin đã đăng nhập.", "Admin có quyền quản lý người dùng.", "Dữ liệu người dùng và vai trò có thể truy cập."],
    mainFlow: [
      "Admin mở màn hình quản lý người dùng.",
      "Frontend tải danh sách người dùng.",
      "Admin chọn xem chi tiết, tạo, cập nhật, đổi trạng thái, xóa hoặc khôi phục người dùng.",
      "Frontend gửi yêu cầu đến UserController.",
      "UserController kiểm tra quyền Admin và validate dữ liệu.",
      "UserService kiểm tra email, vai trò và trạng thái tài khoản.",
      "UserRepository lưu thay đổi vào cơ sở dữ liệu.",
      "Hệ thống ghi SecurityAudit và trả kết quả cho frontend.",
    ],
    alternateFlows: [
      { code: "5a", title: "Dữ liệu người dùng không hợp lệ", steps: ["Hệ thống trả lỗi validate.", "Admin chỉnh sửa lại thông tin."] },
      { code: "6a", title: "Email đã tồn tại hoặc vai trò không hợp lệ", steps: ["Hệ thống không lưu thay đổi.", "Frontend hiển thị lỗi nghiệp vụ."] },
      { code: "7a", title: "Không tìm thấy người dùng", steps: ["Hệ thống không thực hiện thao tác.", "Frontend tải lại danh sách mới nhất."] },
    ],
  },
  {
    code: "UC23",
    slug: "23-phan-quyen-rbac",
    name: "Phân quyền RBAC",
    actors: ["Admin"],
    details: ["Xem danh sách vai trò", "Xem danh sách quyền", "Gán quyền cho vai trò", "Gán vai trò cho user", "Đồng bộ quyền", "Ghi audit phân quyền"],
    classes: ["Role", "Permission", "UserRole", "RolePermission", "User", "SecurityAudit"],
    participants: ["Admin", "Frontend", "RbacController", "RbacService", "RbacRepository", "MongoDB"],
    description: "Admin quản lý vai trò, quyền hạn và quan hệ gán quyền trong hệ thống theo mô hình RBAC.",
    preconditions: ["Admin đã đăng nhập.", "Admin có quyền phân quyền RBAC.", "Danh mục role và permission đã được khởi tạo hoặc có thể đồng bộ."],
    mainFlow: [
      "Admin mở màn hình phân quyền RBAC.",
      "Frontend tải danh sách vai trò, quyền và người dùng liên quan.",
      "Admin chọn gán quyền cho vai trò hoặc gán vai trò cho người dùng.",
      "Frontend gửi yêu cầu đến RbacController.",
      "RbacController kiểm tra quyền Admin và validate dữ liệu.",
      "RbacService kiểm tra role, permission, user và ràng buộc nghiệp vụ.",
      "RbacRepository lưu quan hệ UserRole hoặc RolePermission.",
      "Hệ thống ghi SecurityAudit và trả kết quả cho frontend.",
    ],
    alternateFlows: [
      { code: "5a", title: "Dữ liệu phân quyền không hợp lệ", steps: ["Hệ thống trả lỗi validate.", "Admin chọn lại role, permission hoặc user."] },
      { code: "6a", title: "Role hoặc permission không tồn tại", steps: ["Hệ thống không lưu thay đổi.", "Frontend tải lại catalog quyền."] },
      { code: "7a", title: "Vi phạm ràng buộc phân quyền", steps: ["Hệ thống từ chối thao tác gây mất quyền quản trị cần thiết.", "Admin điều chỉnh phương án phân quyền."] },
    ],
  },
];

export const useCases = rawUseCases.map((useCase) => ({
  ...useCase,
  file: `${useCase.code}-${useCase.slug.slice(3)}.doc`,
}));

export const actorGroups = [
  { folder: "User", actor: "Người dùng", useCaseCodes: ["UC01", "UC02", "UC03", "UC04", "UC05", "UC08", "UC13"] },
  { folder: "Student", actor: "Học viên", useCaseCodes: ["UC06", "UC07", "UC08", "UC13"] },
  { folder: "Teacher", actor: "Giảng viên", useCaseCodes: ["UC09", "UC10", "UC11", "UC12", "UC13"] },
  { folder: "Manager", actor: "Quản lý", useCaseCodes: ["UC11", "UC12", "UC13", "UC14", "UC15", "UC16", "UC17", "UC18", "UC19", "UC20", "UC21"] },
  { folder: "Admin", actor: "Admin", useCaseCodes: ["UC13", "UC14", "UC15", "UC16", "UC17", "UC18", "UC19", "UC20", "UC21", "UC22", "UC23"] },
];

export const actorHierarchy = [
  ["Học viên", "Người dùng"],
  ["Giảng viên", "Học viên"],
  ["Quản lý", "Giảng viên"],
  ["Admin", "Quản lý"],
];

export const actorUseCaseMap = actorGroups.map(({ actor, useCaseCodes }) => [actor, useCaseCodes]);

export function useCaseByCode(code) {
  return useCases.find((useCase) => useCase.code === code);
}
