export const PERMISSION_GROUPS = Object.freeze({
  DASHBOARD: { key: "DASHBOARD", label: "Tổng quan", icon: "home", order: 5 },
  USERS: { key: "USERS", label: "Người dùng", icon: "users", order: 10 },
  CATEGORIES: { key: "CATEGORIES", label: "Danh mục", icon: "folder", order: 20 },
  COURSES: { key: "COURSES", label: "Khóa học", icon: "book-open", order: 30 },
  TEACHERS: { key: "TEACHERS", label: "Giảng viên", icon: "graduation-cap", order: 40 },
  TEACHER_PORTAL: { key: "TEACHER_PORTAL", label: "Trang giáo viên", icon: "school", order: 45 },
  STUDENTS: { key: "STUDENTS", label: "Học viên", icon: "user-check", order: 50 },
  STUDENT_PORTAL: { key: "STUDENT_PORTAL", label: "Trang học viên", icon: "book-open-check", order: 52 },
  CLASSROOMS: { key: "CLASSROOMS", label: "Lớp học", icon: "school", order: 55 },
  ENROLLMENTS: { key: "ENROLLMENTS", label: "Đăng ký học", icon: "clipboard-list", order: 60 },
  SCHEDULES: { key: "SCHEDULES", label: "Lịch học", icon: "calendar-days", order: 70 },
  NOTIFICATIONS: { key: "NOTIFICATIONS", label: "Thông báo", icon: "bell", order: 75 },
  BLOGS: { key: "BLOGS", label: "Bài viết", icon: "file-text", order: 78 },
  PAYMENT_METHODS: { key: "PAYMENT_METHODS", label: "Phương thức thanh toán", icon: "landmark", order: 79 },
  AUDIT: { key: "AUDIT", label: "Audit", icon: "clipboard-check", order: 80 },
  SYSTEM: { key: "SYSTEM", label: "Hệ thống", icon: "shield", order: 99 },
});
